### ISSUE TITLE
[Feature] Async Mode

### ISSUE THREAD

**Issue by Vinyzu** [QIN2DIM/recaptcha-challenger#5]
Will this project be available in async mode some day?
If you dont have the time to, id do it and make a pull requests (i want to use this in Botright...)

**Comment by QIN2DIM** [comment]
I'm still decoupling this module from a closed source project I maintain. I'd like to consider async after this project is stable and running Visual challenge.

If you commit pr before then, I probably won't merge it for a short time, because async is a high-risk operation with a lot of stability issues to consider.

**Comment by Vinyzu** [comment]
Ok, no problem then...
May i ask what your project is about? :P

**Comment by QIN2DIM** [comment]
😁 the next generation captcha for CCP

**Comment by Vinyzu** [comment]
Sorry, whats ccp?
And if u wanna make a captcha, may we contact cause i was messing with some ideas for a new type of captcha...
